### ISSUE TITLE
outdated nuget

### ISSUE THREAD

**Issue by dimants** [onizet/html2openxml#16]
Hi Olivier,

Do you plan to release an updated nuget package? in the latest package (from mid 2016) there is a reference to documentformat.openxml 2.5 while in my project I need to use 2.7.2. I see that you have updated this reference in the source but haven't released it as a package. And, what would be even better, perhaps you can remove the dependency on specific version of documentformat.openxml?

Thanks for the great stuff,

Regards,
Dmitri

**Comment by onizet** [comment]
Hello Dmitri,

Yes I'm still working on it because I wanted to have a dotnetcore1.1 version friendly.
For the coming months I have no time but in mid january/feb I will be able to finish the different tasks and publish a new major version.
The DocumentFormat.OpenXml 2.7.2 supports different framework (netstandard, 3.5, 4.6 etc) so the better for everyone will be to stick with that version. Moreover, previous version got serious bug due to System.IO.Packaging (see [release notes](https://www.nuget.org/packages/DocumentFormat.OpenXml)).

If you want to help, I'm always happy when I received a PR :)

**Comment by onizet** [comment]
Version v2.0 has been released
